### ISSUE TITLE
局域网链接报错4206

### ISSUE THREAD

**Issue by lycaste** [123456fsdaf/GenshinImpact_Lanucher#15]
服务器版本：development分支最新代码
登录器版本：v1.4.2-stable
问题描述：
mac上启动了一个sever（accessAdress设置本机成局域网ip），另一台windows机器可以访问，然后输入账号密码后 一直报错4206
但是windows机器上启动服务器 本机在启动[GenshinImpact_Lanucher]可以登录进去

**Comment by lycaste** [comment]
https://github.com/Grasscutters/Grasscutter/issues/836
用了他里面的这种方法 可以了

**Comment by 123456fsdaf** [comment]
@SwetyCore 来解决

**Comment by SwetyCore** [comment]
已知会导致 502、4206 错误的部分原因：
1. SSL 根证书未信任，或者签发的证书未包含 mihoyo.com / hoyoverse.com / yuanshen.com 域名
2. 代理配置错误，未正确连接到服务器
3. 服务器 config.json 中的 publicIp 配置有误，需要设置为服务器外网 IP 或者本机（运行游戏的机器）能访问的 IP
4. 端口或协议错误，例如服务器运行在 HTTP 协议，但是客户端使用了 HTTPS 连接（较为常见的是dev分支config.json丢失KeystorePassword）
5. Dispatch Server线程异常，导致服务失效，需要重启才行 (已编辑)
 -----------
来自_Gcchinese #常见问题 faq_
