### ISSUE TITLE
[建议]在第一次启动之前先设置路径

### ISSUE THREAD

**Issue by misaka10843** [123456fsdaf/GenshinImpact_Lanucher#2]
如题，因为发现如果没有选择路径而从设置里面切换游戏服务器的话会出现崩溃

而且在设置路径后如果没有设置SF的IP地址在主页面点击服务器游戏也会崩溃（这个建议设置IP后再显示按钮）

**Comment by misaka10843** [comment]
而且在win11 beta中启动器的背景不知道是bug还是什么只有白色🤣
![图片](https://user-images.githubusercontent.com/69132853/167520463-41f1082c-5c74-4a4c-bac9-ad2016d94870.png)

**Comment by misaka10843** [comment]
#3 虽然暂时修复(应该)了下崩溃问题，但是主题问题还是找不到解决方案

**Comment by 123456fsdaf** [comment]
嗯……好久没开github没看到，这个BUG你可以试试更新一下WPF-UI，要不然只能去WPF-UI提问题了，地址如下：https://github.com/lepoco/wpfui

**Comment by misaka10843** [comment]
> 嗯……好久没开github没看到，这个BUG你可以试试更新一下WPF-UI，要不然只能去WPF-UI提问题了，地址如下：https://github.com/lepoco/wpfui 等等，DEV通道吗？

beta通道版本出现的问题

**Comment by misaka10843** [comment]
然后还有个问题就是为什么我每次clone最新的之后都会提示
`XDG0062	未能加载文件或程序集“WPFUI, Culture=neutral”或它的某一个依赖项。系统找不到指定的文件。`
`XDG0062	未能加载文件或程序集“Microsoft.Xaml.Behaviors, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。`

**Comment by 123456fsdaf** [comment]
这一个是UI层库，一个是行为库，如果手动添加能解决的话最好，因为我是把所有资源集成到一个EXE里面的
