### ISSUE TITLE
启动器打开白屏！

### ISSUE THREAD

**Issue by xiaocheng168** [123456fsdaf/GenshinImpact_Lanucher#5]
![图片](https://user-images.githubusercontent.com/43944975/167673507-f3c4ebe6-cee0-4742-ac6d-b1c88c15f3ff.png)
系统：
![图片](https://user-images.githubusercontent.com/43944975/167673852-0adc3dbb-0bca-49a6-b491-362833725182.png)

**Comment by 123456fsdaf** [comment]
请切换系统主题或主题颜色以解决这个问题，因为启动器是使用Win11Mica笔刷制作，往后会追加兼容
